In [1]:
import numpy as np

# Create an 11x11 image with sequential pixel values
image = np.arange(1, 122).reshape(11, 11)
print("11x11 Image:\n", image)


11x11 Image:
 [[  1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22]
 [ 23  24  25  26  27  28  29  30  31  32  33]
 [ 34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55]
 [ 56  57  58  59  60  61  62  63  64  65  66]
 [ 67  68  69  70  71  72  73  74  75  76  77]
 [ 78  79  80  81  82  83  84  85  86  87  88]
 [ 89  90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120 121]]


In [2]:
def traditional_averaging(image, mask_size):
    import numpy as np

    pad_size = mask_size // 2
    padded_image = np.pad(image, ((0, 0), (pad_size, pad_size)), mode='constant', constant_values=0)
    center_row = padded_image[5, :]  # Center row (zero-padded)

    output_row = []
    operation_count = {'additions': 0, 'multiplications': 0, 'divisions': 0}

    for i in range(len(image[0])):
        # Extract the window
        window = center_row[i:i + mask_size]
        # Perform averaging
        sum_pixels = sum(window)
        operation_count['additions'] += mask_size - 1
        average = sum_pixels / (mask_size ** 2)
        operation_count['divisions'] += 1
        output_row.append(average)

    return np.array(output_row), operation_count

image = np.arange(1, 122).reshape(11, 11)
output, operations = traditional_averaging(image, mask_size=5)
print("Output Row (Traditional):", output)
print("Operations (Traditional):", operations)


Output Row (Traditional): [ 6.84  9.2  11.6  11.8  12.   12.2  12.4  12.6  12.8  10.32  7.8 ]
Operations (Traditional): {'additions': 44, 'multiplications': 0, 'divisions': 11}


In [3]:
def optimized_averaging(image, mask_size):
    import numpy as np

    pad_size = mask_size // 2
    padded_image = np.pad(image, ((0, 0), (pad_size, pad_size)), mode='constant', constant_values=0)
    center_row = padded_image[5, :]  # Center row (zero-padded)

    output_row = []
    operation_count = {'additions': 0, 'subtractions': 0, 'divisions': 0}

    # Calculate the first window
    window = center_row[:mask_size]
    sum_pixels = sum(window)
    operation_count['additions'] += mask_size - 1
    output_row.append(sum_pixels / (mask_size ** 2))
    operation_count['divisions'] += 1

    # Slide the window across
    for i in range(1, len(image[0])):
        sum_pixels += center_row[i + mask_size - 1] - center_row[i - 1]
        operation_count['additions'] += 1
        operation_count['subtractions'] += 1
        average = sum_pixels / (mask_size ** 2)
        operation_count['divisions'] += 1
        output_row.append(average)

    return np.array(output_row), operation_count

output_optimized, operations_optimized = optimized_averaging(image, mask_size=5)
print("Output Row (Optimized):", output_optimized)
print("Operations (Optimized):", operations_optimized)


Output Row (Optimized): [ 6.84  9.2  11.6  11.8  12.   12.2  12.4  12.6  12.8  10.32  7.8 ]
Operations (Optimized): {'additions': 14, 'subtractions': 10, 'divisions': 11}
